server:
  port: 8080
spring:
  application:
    name: bookserver
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${db.host}:3306/book?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&createDatabaseIfNotExist=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  # Redis配置
#  redis:
#    host: 159.75.208.179
#    port: 6379
#    password: root
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

      #      database: 1
#      # 读超时
#      timeout: 3000
#      # 连接超时
#      connectTimeout: 5000
      # Lettuce连接池
#      lettuce:
#        pool:
#          # 最小空闲连接
#          min-idle: 5
#          # 最大空闲连接
#          max-idle: 10
#          # 最大连接数
#          max-active: 100
#          # 连接分配应该阻塞的最大时间
#          max-wait: 2000

#  jackson:
#    time-zone: Asia/Shanghai
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: true